spring:
  application:
    name: event-consumers

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      keepalive-time: 30_000 # keep connection alive by testing them every 30s
      minimum-idle: 10 # ensure pool does not die when idle

  sql:
    init:
      mode: ${DB_MODE}
      data-locations: classpath:schema.sql


  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /


app:
  rabbitmq:
    matches:
      exchange: ${RABBITMQ_MATCHES_EXCHANGE}
      queue: ${RABBITMQ_MATCHES_QUEUE}
      routing-key: ${RABBITMQ_MATCHES_ROUTING_KEY}
    results:
      exchange: ${RABBITMQ_RESULTS_EXCHANGE}
      queue: ${RABBITMQ_RESULTS_QUEUE}
      routing-key: ${RABBITMQ_RESULTS_ROUTING_KEY}
    transactions:
      exchange: ${RABBITMQ_TRANSACTIONS_EXCHANGE}
      queue: ${RABBITMQ_TRANSACTIONS_QUEUE}
      routing-key: ${RABBITMQ_TRANSACTIONS_ROUTING_KEY}
    wallets:
      exchange: ${RABBITMQ_WALLETS_EXCHANGE}
      queue: ${RABBITMQ_WALLETS_QUEUE}
      routing-key: ${RABBITMQ_WALLETS_ROUTING_KEY}

server:
  port: ${APP_PORT}


logging:
  config: classpath:event-consumers-logback.xml
  level:
    root: INFO
    com.bixx.event_consumer: ${LOGGING_LEVEL}
    org.springframework.jdbc: ${LOGGING_LEVEL}
    org.apache.coyote: INFO